---
- hosts: all
  become: True
  user: root
  connection: ssh # or paramiko

  tasks:
  - name: add pms repo for centos 6.7
    yum_repository:
      name: pms_centos
      description: pms yum repo
      baseurl: http://192.168.7.52/repo/CentOS/6/7
      #baseurl: http://192.168.7.52/repo
      async: 0

  - name: add pms repo for Ubuntu
    apt_repository: 
      repo: deb http://192.168.7.52/repo/Ubuntu/Ubuntu16.04 xenial main
      state: present
      filename: 'pms_ubuntu_repo'    
