---
- hosts: all
  become: True
  user: root
  connection: ssh # or paramiko

  tasks:
  - name: add Mapbox repo
    apt_repository: repo='ppa:developmentseed/mapbox' state=present update_cache=yes
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
