---
- hosts: all
  become: True
  user: root
  connection: ssh # or paramiko

  tasks:
    - name: compare package
      command: >
        rpm -qa
          | grep
          package name
          
        yum check-update
          | grep
          package name
