- hosts: all
  tasks:
  - name: Installing useful packages
    apt:
      name: "{{ item }}"
      update_cache: yes
      cache_valid_time: 3600
    with_items:
        - vim        
        - ntp
        - wget
        - unzip
        - vsftpd
        - udev
        - xkeyboard-config
        - gmp
        - efibootmgr
        - crda   
    
